/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assign;

import static assign.Assign.*;
import static assign.click.allvertex;
import static assign.click.pts;
import static assign.mark.*;
import static assign.point.*;
import javax.swing.*;
import java.util.*;

/**
 *
 * @author kaun_meet
 */
public class Modifyvertex extends javax.swing.JFrame {

    /**
     * Creates new form Modifyvertex
     */
    public Modifyvertex() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        change1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        change3 = new javax.swing.JTextField();
        change4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Vertex needed to be changed");

        jLabel3.setText("New x coordinate");

        jLabel4.setText("New y coordinate");

        change3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change3ActionPerformed(evt);
            }
        });

        jButton2.setText("Change");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(change4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(change3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(change1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jButton2)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(change1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(change3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(change4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void change3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_change3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {

            String a, b, c, d;
            a = change1.getText().trim();
//        b = change2.getText().trim();
            c = change3.getText().trim();
            d = change4.getText().trim();
            int valid1 = mark.cnof(a);
//        int valid2 = mark.cnof(b);
            int valid2 = 1;
            int wc = Integer.parseInt(c);
            int wd = Integer.parseInt(d);
            int valid3 = mark.ccor(wc, wd);
            if (a.isEmpty() || c.isEmpty() || d.isEmpty()) {
                JOptionPane.showMessageDialog(null, "kindly enter all details");
//            System.out.println("kindly enter all details");
            } else {
                if (false) {
                    JOptionPane.showMessageDialog(null, "name is wrongly written");

//                System.out.println("name is wrongly written");
                } else if (valid2 == -1) {
                    JOptionPane.showMessageDialog(null, "new name is wrong");

//                System.out.println("new name is wrong");
                } else if (valid3 == -1) {
                    JOptionPane.showMessageDialog(null, "New Coordinates are occupied");

//                System.out.println("New Coordinates are occupied");
                } else if (valid3 == -2) {
                    JOptionPane.showMessageDialog(null, "Coordinated should be valid");

//                System.out.println("Coordinated should be valid");
                } else {
                    int cc = mark.checkvertex(a);
                    if (cc == -1) {
                        JOptionPane.showMessageDialog(null, "no vertex with such a name");

//                    System.out.println("no vertex with such a name");
                    } else {
//                    vertexlist.get(cc).nameofvertex = b;

//                    vertexlist.get(cc).xcoordinate = wc;
//                    vertexlist.get(cc).ycoordinate = wd;
                        pts.get(cc).x = wc;
                        pts.get(cc).y = wd;
                        allvertex.get(cc).xcoor = wc;
                        allvertex.get(cc).ycoor = wd;
                        JOptionPane.showMessageDialog(null, "operation successfull");

//System.out.println("operation successfull");
                    }
                }

            }
//        for (int i = 0; i < vertexlist.size(); i++) {
//            System.out.println(vertexlist.get(i).nameofvertex);
//        }
//        for (int i = 0; i < edgelist.size(); i++) {
//            System.out.println(edgelist.get(i).from + " " + edgelist.get(i).to + " " + edgelist.get(i).weight);
//        }
// TODO add your handling code here:
//repaint();

            this.dispose();
        } catch (Exception e) {

        }


    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modifyvertex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modifyvertex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modifyvertex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modifyvertex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modifyvertex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField change1;
    private javax.swing.JTextField change3;
    private javax.swing.JTextField change4;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
