/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assign;

import static assign.Assign.*;
import static assign.click.allvertex;
import static assign.mark.*;
import static assign.point.*;
import javax.swing.*;
import java.util.*;

/**
 *
 * @author kaun_meet
 */
public class Searchvertex extends javax.swing.JFrame {

    /**
     * Creates new form Searchvertex
     */
    public Searchvertex() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bhau = new javax.swing.JTextField();
        CHECK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Element to be searched");

        bhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhauActionPerformed(evt);
            }
        });

        CHECK.setText("Perform the search");
        CHECK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHECKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addComponent(bhau, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(CHECK)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(66, 66, 66)
                .addComponent(CHECK)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bhauActionPerformed

    private void CHECKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHECKActionPerformed
        try {
            String gh = bhau.getText();
            if (gh.isEmpty()) {
                JOptionPane.showMessageDialog(null, "SEARCH NOT DONE");

//    System.out.println("SEARCH NOT DONE");
            } else {
                int v = mark.cnof(gh);
                if (false) {
                    JOptionPane.showMessageDialog(null, "wrongly format name");

//        System.out.println("wrongly format name");  
                } else {
                    int find = mark.checkvertex(gh);
                    if (find == -1) {
                        JOptionPane.showMessageDialog(null, "element NOT FOUND");

//        System.out.println("element NOT FOUND");
                    } else {
//        System.out.println("FOUND --  "+vertexlist.get(find).nameofvertex+" "+vertexlist.get(find).xcoordinate+" "+vertexlist.get(find).ycoordinate);
                        JOptionPane.showMessageDialog(null, "FOUND --  " + allvertex.get(find).namevertex + " " + allvertex.get(find).xcoor + " " + allvertex.get(find).ycoor);

//System.out.println("FOUND --  "+allvertex.get(find).namevertex+" "+allvertex.get(find).xcoor+" "+allvertex.get(find).ycoor);
                    }
                }
            }

// for(int i=0;i<vertexlist.size();i++){
//            System.out.println(vertexlist.get(i).nameofvertex);
////        }
//        for(int i=0;i<edgelist.size();i++){
//            System.out.println(edgelist.get(i).from+" "+edgelist.get(i).to+" "+edgelist.get(i).weight);
//        }
            // TODO add your handling code here:
            this.dispose();
        } catch (Exception e) {
        }


    }//GEN-LAST:event_CHECKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Searchvertex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Searchvertex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Searchvertex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Searchvertex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Searchvertex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CHECK;
    private javax.swing.JTextField bhau;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
